# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'instaClone' do
  pod 'AppCenter/Push', '~> 2.1.0'
  pod 'AppCenter/Crashes', '~> 2.1.0'
  pod 'AppCenter/Analytics', '~> 2.1.0'
  pod 'AppCenterReactNativeShared', '~> 2.1.0'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for instaClone

  

  platform :ios, '9.0'
  target 'instaCloneTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'instaClone-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for instaClone-tvOS

  target 'instaClone-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
